//
//  EditorCatalogTest.kt — the EDITOR CATALOG harness: keeps the web-canvas catalog
//  (OpenSource/Documentation/reference/stack-elements.json — GENERATED by
//  ClosedSource/scripts/generate_editor_catalog.rb) in lock-step with the runtime.
//
//  The catalog is the 1:1 contract the web preview editor ("the canvas") loads to know every
//  renderable DSX tag: typed attributes with defaults, events, aliases, platform support, and
//  one canonical example per tag. This test is the SIMULATION HALF of the sync law (the
//  generator's --check mode is the byte-compare half, wired next to check_style_catalog in
//  codemagic.yaml):
//
//  FAILS on:
//   • an ElementSpec-registered tag missing from the catalog, or whose catalog attribute
//     defaults / aliases drift from the enforced spec constants (catalog ⊇ specs, values equal);
//   • an example snippet that does not parse via StackXML, does not contain its own tag, or
//     uses an attribute the catalog itself does not declare for that tag (universal attributes,
//     child markers, style-catalog keys, and arg:*/:ios/:android conventions allowed) —
//     the "examples can never rot" rule;
//   • a platforms field that disagrees with the elements-gaps.json buckets (dclass/missing
//     ⇒ iOS-only; a registered spec ⇒ both platforms);
//   • a catalog tag unknown to the census (not a Conformance fixture tag and not one of the
//     13 kernel structural/declaration tags), or a census tag missing from the catalog;
//   • an `events` array that disagrees with the entry's own on:* attributes (the invariant
//     the generator guarantees — locked here so hand edits can't sneak in).
//
package despia.engine.render

import despia.engine.StackNode
import despia.engine.StackXML
import despia.engine.json
import org.junit.Assert.fail
import org.junit.Test
import java.io.File

class EditorCatalogTest {

    // Finder/iCloud conflict copies are workspace artefacts, not additional contracts.
    private val finderConflictCopy = Regex(".+ [0-9]+\\.json")

    // The kernel structural/declaration tags (the Conformance elements/README census — they
    // register logic and render nothing, so they have no parity fixtures).
    private val structuralTags = setOf(
        "head", "attribute", "expects", "event", "variable", "formula", "action",
        "script", "watch", "style", "component", "slot", "node", "tool",
    )

    // The corpus + catalog sit in the open drop — walk up from the working dir to the repo
    // root (the ElementParityTest convention). Missing catalog = loud failure, never a skip.
    private fun repoRoot(): File {
        var dir = File(System.getProperty("user.dir") ?: ".").absoluteFile
        while (true) {
            if (File(dir, "OpenSource/Documentation/reference/stack-elements.json").isFile) return dir
            dir = dir.parentFile
                ?: error("OpenSource/Documentation/reference/stack-elements.json not found walking up " +
                    "from ${System.getProperty("user.dir")} — run: ruby ClosedSource/scripts/generate_editor_catalog.rb")
        }
    }

    @Suppress("UNCHECKED_CAST")
    private fun obj(file: File): Map<String, Any?> =
        (json(file.readText()).foundationValue as? Map<String, Any?>)
            ?: error("${file.name}: not a JSON object")

    @Suppress("UNCHECKED_CAST")
    private fun map(v: Any?): Map<String, Any?> = (v as? Map<String, Any?>) ?: emptyMap()

    /// Canonical string form shared with ElementParityTest: numbers unpadded ("8", not "8.0"),
    /// booleans "true"/"false", null = no default.
    private fun canon(v: Any?): String? = when (v) {
        null -> null
        is Boolean -> if (v) "true" else "false"
        is Double -> if (v == Math.floor(v) && !v.isInfinite()) v.toLong().toString() else v.toString()
        is Int -> v.toString()
        is Long -> v.toString()
        else -> v.toString()
    }

    private fun catalog(): Map<String, Any?> =
        obj(File(repoRoot(), "OpenSource/Documentation/reference/stack-elements.json"))

    private fun fixtureFiles(dir: File): List<File> =
        dir.listFiles { f ->
            f.isFile && f.extension == "json" && f.name != "elements-gaps.json" &&
                !finderConflictCopy.matches(f.name)
        }?.sortedBy { it.name } ?: emptyList()

    // ── 1. catalog ⊇ enforced ElementSpecs, values equal ─────────────────────────────────
    @Test
    fun catalogCoversEnforcedSpecs() {
        val elements = map(catalog()["elements"])
        val failures = mutableListOf<String>()
        for ((tag, spec) in ElementSpecs.all()) {
            val entry = map(elements[tag])
            if (entry.isEmpty()) {
                failures += "<$tag>: registered ElementSpec but NO catalog entry — regenerate " +
                    "(ruby ClosedSource/scripts/generate_editor_catalog.rb)"
                continue
            }
            val catAliases = (entry["aliases"] as? List<Any?>)?.map { it.toString() }?.toSet() ?: emptySet()
            if (catAliases != spec.aliases.toSet()) {
                failures += "<$tag> aliases: catalog ${catAliases.sorted()} vs spec ${spec.aliases.sorted()}"
            }
            val catAttrs = map(entry["attributes"])
            for ((name, specDefault) in spec.attributes) {
                val catAttr = map(catAttrs[name])
                if (!catAttrs.containsKey(name)) {
                    failures += "<$tag> attribute `$name`: enforced by ElementSpec but missing from the catalog"
                    continue
                }
                val catDefault = canon(catAttr["default"])
                if (catDefault != canon(specDefault)) {
                    failures += "<$tag> attributes.$name: default drift — catalog `$catDefault` vs spec `${canon(specDefault)}`"
                }
            }
        }
        if (failures.isNotEmpty()) {
            fail("EDITOR CATALOG vs ElementSpec violations (${failures.size}):\n - " + failures.joinToString("\n - "))
        }
    }

    // ── 2. every example SIMULATES: parses via StackXML, uses only declared attributes ────
    @Test
    fun examplesSimulate() {
        val root = repoRoot()
        val cat = catalog()
        val elements = map(cat["elements"])
        val components = map(cat["components"])
        val aliases = map(cat["aliases"]).mapValues { it.value.toString() }
        val universal = map(cat["universalAttributes"]).keys
        val markers = map(cat["childMarkers"]).keys

        // the style panel's keys (+ aliases) are legal on any element — the $ref side.
        val styleKeys = mutableSetOf<String>()
        val styleCatalog = obj(File(root, "OpenSource/Documentation/reference/stack-style-properties.json"))
        for (group in (styleCatalog["groups"] as? List<Any?>) ?: emptyList()) {
            for (prop in (map(group)["properties"] as? List<Any?>) ?: emptyList()) {
                val p = map(prop)
                p["key"]?.let { styleKeys += it.toString() }
                for (a in (p["aliases"] as? List<Any?>) ?: emptyList()) styleKeys += a.toString()
            }
        }
        require(styleKeys.isNotEmpty()) { "stack-style-properties.json yielded no style keys" }

        fun canonicalTag(tag: String): String? = when {
            elements.containsKey(tag) -> tag
            aliases.containsKey(tag) -> aliases[tag]
            else -> null
        }

        fun walk(node: StackNode, visit: (StackNode) -> Unit) {
            visit(node)
            node.children.forEach { walk(it, visit) }
        }

        val failures = mutableListOf<String>()
        fun checkExample(owner: String, tag: String, example: String) {
            val parsed = StackXML.parse(example)
            if (parsed == null) {
                failures += "$owner: example does not parse via StackXML — $example"
                return
            }
            var found = false
            walk(parsed) { node ->
                if (node.tag == tag || aliases[node.tag] == tag) found = true
                val nodeCanonical = canonicalTag(node.tag) ?: return@walk // component invocations etc.
                val entry = map(elements[nodeCanonical])
                if (entry["openAttributes"] == true) return@walk // formula/action/style take named inputs
                val declared = map(entry["attributes"]).keys
                for (attr in node.attrs.keys) {
                    val base = attr.removeSuffix(":ios").removeSuffix(":android")
                    val ok = base in declared || base in universal || base in markers ||
                        base in styleKeys || base.startsWith("arg:")
                    if (!ok) {
                        failures += "$owner: example's <${node.tag}> uses `$attr` which the catalog does not " +
                            "declare for <$nodeCanonical> (not universal, not a child marker, not a style key)"
                    }
                }
            }
            if (!found) failures += "$owner: example never uses its own tag <$tag> — $example"
        }

        for ((tag, raw) in elements) {
            val entry = map(raw)
            val example = entry["example"] as? String
            if (example.isNullOrBlank()) { failures += "<$tag>: catalog entry has no example"; continue }
            checkExample("<$tag>", tag, example)
        }
        for ((key, raw) in components) {
            val entry = map(raw)
            val tag = entry["tag"] as? String ?: key
            val example = entry["example"] as? String
            if (example.isNullOrBlank()) { failures += "component $key: no example"; continue }
            val parsed = StackXML.parse(example)
            if (parsed == null) { failures += "component $key: example does not parse — $example"; continue }
            var found = false
            walk(parsed) { node -> if (node.tag == tag) found = true }
            if (!found) failures += "component $key: example never uses its tag <$tag>"
        }

        if (failures.isNotEmpty()) {
            fail("EDITOR CATALOG example violations (${failures.size}):\n - " + failures.joinToString("\n - "))
        }
    }

    // ── 3. platforms agree with the elements-gaps.json buckets ────────────────────────────
    @Test
    fun platformsAgreeWithGaps() {
        val root = repoRoot()
        val gaps = obj(File(root, "OpenSource/Conformance/elements/elements-gaps.json"))
        val missing = (gaps["missing"] as? List<Any?>)?.map { it.toString() }?.toSet() ?: emptySet()
        val module = ((gaps["module"] as? Map<*, *>)?.get("tags") as? List<Any?>)?.map { it.toString() }?.toSet() ?: emptySet()
        val dclass = ((gaps["dclass"] as? Map<*, *>)?.get("tags") as? List<Any?>)?.map { it.toString() }?.toSet() ?: emptySet()

        val elements = map(catalog()["elements"])
        val failures = mutableListOf<String>()
        for ((tag, raw) in elements) {
            val platforms = (map(raw)["platforms"] as? List<Any?>)?.map { it.toString() } ?: emptyList()
            if (platforms.isEmpty() || !platforms.contains("ios")) {
                failures += "<$tag>: platforms $platforms — every catalog tag ships on iOS (the reference renderer)"
            }
            when {
                tag in dclass && platforms.contains("android") ->
                    failures += "<$tag>: D-class (iOS-only by decision, elements-gaps.json) but catalog claims android"
                tag in missing && platforms.contains("android") ->
                    failures += "<$tag>: allowlisted `missing` on Android but catalog claims android"
                ElementSpecs.all().containsKey(tag) && !platforms.contains("android") ->
                    failures += "<$tag>: has a registered Android ElementSpec but catalog omits android"
                tag in module && !platforms.contains("ios") ->
                    failures += "<$tag>: module-implemented tag must at least list ios"
            }
        }
        if (failures.isNotEmpty()) {
            fail("EDITOR CATALOG platform violations (${failures.size}):\n - " + failures.joinToString("\n - "))
        }
    }

    // ── 4. census: fixtures + structural tags == catalog elements, exactly; events invariant ─
    @Test
    fun censusComplete() {
        val root = repoRoot()
        val fixturesDir = File(root, "OpenSource/Conformance/elements")
        val fixtureTags = fixtureFiles(fixturesDir).map { file ->
            val tag = obj(file)["tag"].toString()
            require(file.nameWithoutExtension == tag) {
                "${file.name}: canonical fixture filename must be `$tag.json`"
            }
            tag
        }.toSet()
        require(fixtureTags.isNotEmpty()) { "element parity corpus is empty" }

        val elements = map(catalog()["elements"])
        val failures = mutableListOf<String>()

        for (tag in fixtureTags) {
            if (!elements.containsKey(tag)) {
                failures += "<$tag>: Conformance fixture exists but the catalog omits it — the census law " +
                    "(regenerate: ruby ClosedSource/scripts/generate_editor_catalog.rb)"
            }
        }
        for ((tag, raw) in elements) {
            val entry = map(raw)
            val kind = entry["kind"]?.toString()
            when {
                kind == "structural" && tag !in structuralTags ->
                    failures += "<$tag>: structural catalog entry unknown to the kernel structural census"
                kind != "structural" && tag !in fixtureTags ->
                    failures += "<$tag>: catalog tag has NO Conformance fixture — new elements land fixture-first"
            }
            // events == the on:* attributes, prefix stripped, sorted (the generator's invariant).
            val events = (entry["events"] as? List<Any?>)?.map { it.toString() } ?: emptyList()
            val derived = map(entry["attributes"]).keys.filter { it.startsWith("on:") }
                .map { it.removePrefix("on:") }.sorted()
            if (events != derived) {
                failures += "<$tag>: events $events disagree with on:* attributes $derived"
            }
        }
        for (tag in structuralTags) {
            if (!elements.containsKey(tag)) failures += "<$tag>: kernel structural tag missing from the catalog"
        }

        if (failures.isNotEmpty()) {
            fail("EDITOR CATALOG census violations (${failures.size}):\n - " + failures.joinToString("\n - "))
        }
    }
}
