//
//  Strings.kt — the KERNEL localization seam (Kotlin twin of DSXStrings.swift;
//  string-table lookup, nothing more).
//
//  "Write the app in English" is the authoring model: the ENGLISH SOURCE STRING is the key
//  (gettext-style — no manual key management), and per-locale tables map it to a translation.
//  The kernel only RESOLVES: it loads a table and looks strings up at the render seam (the text
//  components call `DSXStrings.localize(s)` on their resolved value). Where tables COME FROM is
//  never the kernel's business (Article 1 — it names nobody):
//
//    • BUILD tier: `Strings.<lang>.json` in the app bundle — flat `{ "Save": "Sichern", … }` —
//      generated by the build pipeline (machine-translated + human-reviewable) or hand-written.
//      `<lang>` is a lowercase BCP-47 tag: `de`, `pt-br`; the full tag is tried, then the bare
//      language.
//    • RUNTIME tier: `global.strings.<lang>` (a dict a module / OTA delivery writes) MERGES OVER
//      the bundle table — the seam a dynamic-translation module fills later. Bump
//      `global.strings.version` after writing so live surfaces re-resolve.
//    • `global.locale` (e.g. "de") OVERRIDES the device language — an in-app language switcher is
//      one state write.
//
//  FAIL-OPEN BY CONSTRUCTION (Article 7): no table, no match, English device, empty string —
//  the input returns unchanged, byte-for-byte; an app that ships no tables pays one dictionary
//  miss. Interpolated templates ("Hello {{name}}") resolve BEFORE this seam, so only their
//  exact rendered form can match — static UI chrome (the overwhelming bulk of app text) is
//  covered; per-user composites stay source-language until the dynamic-translation module lands.
//  MAIN-THREAD (render-seam) — statics need no locking. Same contract here: the cache is
//  unsynchronized BY DESIGN; the host calls `localize` on the UI thread only.
//
//  Pure-JVM seams (PLAN.md ground rule 3 — the Swift file's three platform touches):
//    • loader — Bundle.main's `Strings.<lang>.json` lookup becomes `(lang) -> JSON text?`,
//      default null (no bundle tier — an app that ships no tables pays one null check). The
//      text is parsed with the kernel's own `json(…)` (Json.kt) — invalid JSON fails open,
//      exactly like Swift's `try?` JSONSerialization.
//    • statePath — `DSX.state.getPath(path)` becomes `(dot-path) -> Any?`, default inert
//      (null; the Jse.stateVars pattern). Serves `locale`, `strings.version`, and the
//      runtime `strings.<lang>` overlay.
//    • deviceLang — Swift reads `Locale.preferredLanguages.first` ONCE (it goes through
//      UserDefaults, far too heavy per localized string per render; a device-language change
//      relaunches the app). Here it seeds once from `java.util.Locale.getDefault()` (which
//      reflects the device locale on Android) and stays a settable var — tests, or a host
//      wanting explicit control. IN-APP switching goes through `global.locale`, which stays
//      live below on both platforms.
//

package despia.engine

import java.util.Locale

object DSXStrings {

    private var table: Map<String, String> = emptyMap()
    private var loadedLang = "__none"
    private var loadedVersion = ""

    /// Seam: the BUILD tier — `Strings.<lang>.json`'s text for a candidate tag, or null.
    var loader: ((String) -> String?)? = null

    /// Seam: `DSX.state.getPath` — the app-wide reactive store (`global.*`); default inert.
    var statePath: (String) -> Any? = { null }

    /// Seam: the device's preferred language, read once (see header). Lowercase BCP-47.
    var deviceLang: String = Locale.getDefault().toLanguageTag().lowercase()

    /// Translate a rendered string through the active locale table. Identity when there is no
    /// table, no match, or the source language is active — never null, never throws.
    /// NOTE the runtime-table contract: a writer of `global.strings.<lang>` MUST bump
    /// `global.strings.version` afterwards — the table reloads only on a (lang, version) change,
    /// deliberately, so live surfaces don't re-walk state tables per rendered string.
    fun localize(s: String): String {
        if (s.isEmpty()) return s
        val lang = resolvedLang()
        val version = statePath("strings.version")?.toString() ?: ""
        if (lang != loadedLang || version != loadedVersion) load(lang, version)
        if (table.isEmpty()) return s
        return table[s] ?: s
    }

    /// `global.locale` (an in-app switcher's write) → the device's preferred language → "en".
    private fun resolvedLang(): String {
        val o = statePath("locale") as? String
        if (o != null && o.isNotEmpty()) return o.lowercase()
        return deviceLang
    }

    /// (Re)load the table for `lang`: the bundle tier under the runtime tier, full tag then bare
    /// language. English (the source language) and misses resolve to the empty table — identity.
    private fun load(lang: String, version: String) {
        loadedLang = lang
        loadedVersion = version
        table = emptyMap()
        val bare = lang.takeWhile { it != '-' && it != '_' }
        for (candidate in listOf(lang, bare)) {
            if (candidate.isEmpty() || candidate == "en") continue
            val merged = LinkedHashMap<String, String>()
            val text = loader?.invoke(candidate)
            if (text != null) {
                val obj = json(text).foundationValue as? Map<*, *>
                if (obj != null) {
                    for ((k, v) in obj) if (k is String && v is String) merged[k] = v
                }
            }
            // Swift's `as? [String: Any]` is all-or-nothing on the keys — mirror that.
            val runtime = statePath("strings.$candidate") as? Map<*, *>
            if (runtime != null && runtime.keys.all { it is String }) {
                for ((k, v) in runtime) if (v is String) merged[k as String] = v   // runtime tier wins
            }
            if (merged.isNotEmpty()) { table = merged; return }
        }
    }
}
