//
//  DSXStrings.swift — the KERNEL localization seam (string-table lookup, nothing more).
//
//  "Write the app in English" is the authoring model: the ENGLISH SOURCE STRING is the key
//  (gettext-style — no manual key management), and per-locale tables map it to a translation.
//  The kernel only RESOLVES: it loads a table and looks strings up at the render seam (the text
//  components call `DSXStrings.localize(_:)` on their resolved value). Where tables COME FROM is
//  never the kernel's business (Article 1 — it names nobody):
//
//    • BUILD tier: `Strings.<lang>.json` in the app bundle — flat `{ "Save": "Sichern", … }` —
//      generated by the build pipeline (machine-translated + human-reviewable) or hand-written.
//      `<lang>` is a lowercase BCP-47 tag: `de`, `pt-br`; the full tag is tried, then the bare
//      language.
//    • RUNTIME tier: `global.strings.<lang>` (a dict a module / OTA delivery writes) MERGES OVER
//      the bundle table — the seam a dynamic-translation module fills later. Bump
//      `global.strings.version` after writing so live surfaces re-resolve.
//    • `global.locale` (e.g. "de") OVERRIDES the device language — an in-app language switcher is
//      one state write.
//
//  FAIL-OPEN BY CONSTRUCTION (Article 7): no table, no match, English device, empty string —
//  the input returns unchanged, byte-for-byte; an app that ships no tables pays one dictionary
//  miss. Interpolated templates ("Hello {{name}}") resolve BEFORE this seam, so only their
//  exact rendered form can match — static UI chrome (the overwhelming bulk of app text) is
//  covered; per-user composites stay source-language until the dynamic-translation module lands.
//  MAIN-THREAD (render-seam) — statics need no locking.
//
import Foundation

public enum DSXStrings {

    private static var table: [String: String] = [:]
    private static var loadedLang = "__none"
    private static var loadedVersion = ""

    /// Translate a rendered string through the active locale table. Identity when there is no
    /// table, no match, or the source language is active — never nil, never throws.
    /// NOTE the runtime-table contract: a writer of `global.strings.<lang>` MUST bump
    /// `global.strings.version` afterwards — the table reloads only on a (lang, version) change,
    /// deliberately, so live surfaces don't re-walk state tables per rendered string.
    public static func localize(_ s: String) -> String {
        guard !s.isEmpty else { return s }
        let lang = resolvedLang()
        let version = (DSX.state.getPath("strings.version").map { "\($0)" }) ?? ""
        if lang != loadedLang || version != loadedVersion { load(lang, version: version) }
        guard !table.isEmpty else { return s }
        return table[s] ?? s
    }

    /// The device's preferred language, read ONCE — `Locale.preferredLanguages` goes through
    /// UserDefaults, far too heavy per localized string per render. A device-language change
    /// relaunches the app; IN-APP switching goes through `global.locale`, which stays live below.
    private static let deviceLang = (Locale.preferredLanguages.first ?? "en").lowercased()

    /// `global.locale` (an in-app switcher's write) → the device's preferred language → "en".
    private static func resolvedLang() -> String {
        if let o = DSX.state.getPath("locale") as? String, !o.isEmpty { return o.lowercased() }
        return deviceLang
    }

    /// (Re)load the table for `lang`: the bundle tier under the runtime tier, full tag then bare
    /// language. English (the source language) and misses resolve to the empty table — identity.
    private static func load(_ lang: String, version: String) {
        loadedLang = lang
        loadedVersion = version
        table = [:]
        let bare = String(lang.prefix(while: { $0 != "-" && $0 != "_" }))
        for candidate in [lang, bare] where !candidate.isEmpty && candidate != "en" {
            var merged: [String: String] = [:]
            if let url = Bundle.main.url(forResource: "Strings.\(candidate)", withExtension: "json"),
               let data = try? Data(contentsOf: url),
               let obj = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any] {
                for (k, v) in obj { if let s = v as? String { merged[k] = s } }
            }
            if let runtime = DSX.state.getPath("strings.\(candidate)") as? [String: Any] {
                for (k, v) in runtime { if let s = v as? String { merged[k] = s } }   // runtime tier wins
            }
            if !merged.isEmpty { table = merged; return }
        }
    }
}
